### ISSUE TITLE
Bug: Crashes randomly - no visual flyout at all 

### ISSUE THREAD

**Issue by mgallub1** [ShankarBUS/ModernFlyouts#128]
**Describe the bug:**
The app seems to close randomly. I change volume or brightness and notice nothing comes up on screen at all. Then I see that it disappeared from the taskbar.

**To Reproduce:**
not sure

**OS Version:**
 - Windows 10 Version: Windows 10 2004 Home Edition

**ModernFlyouts Version:**
 - Version: v0.7.1

**Comment by NotExactlyMeButMeh** [comment]
I've got a similar issue, however it seems to be caused by media such as music from Spotify changing too many times. Cover art will eventually fail to update on song change until it will inevitably crash and you must restart the program. Last time it crashed it caused the start menu and other explorer aspects to lag behind inputs by a number of seconds.

**To Reproduce:**
Steps to reproduce the behavior:
1. Open ModernFlyouts
2. Ensure that it is working by toggling something such as Caps Lock/Num Lock.
3. Start playing or if you are already playing media through a platform such as Spotify, continue.
4. Attempt to change songs multiple times, forwards or backwards it does not matter. Use the media keys or the buttons on the flyout to do this.
5. Watch as cover art will stop updating and the app will eventually crash.

**OS Version:**

- Windows 10 Version: Windows 10 1909 Home Edition

**ModernFlyouts Version:**

 - Version: v0.7.1 (installed from the GitHub Mxis-bundle package)

**Comment by ShankarBUS** [comment]
Sorry for the late reply and the bug guys 😅.
 
@NotExactlyMeButMeh, the bug you experience is filed on #100.

That's the reason behind this bug.

You can keep up-to-date on that issue.

However I don't understand @mgallub1's issue. So I will keep this issue open until they provide a solid way to reproduce this bug.

**Comment by kojuan** [comment]
Following.

It still exists on Windows 10 Build 20H2 (October 2020 Update).
hope to fix the bug asap :)

**Comment by ShankarBUS** [comment]
This bug is related to .NET 5, not the OS.

This could be solved with a future .NET 5 release.

Everything were working fine while we were using .NET Core 3.1 😔

**Comment by kojuan** [comment]
> This bug is related to .NET 5, not the OS.
> 
> This could be solved with a future .NET 5 release.
> 
> Everything were working fine while we were using .NET Core 3.1 😔

I see.  Thanks for the information.

**Comment by mgallub1** [comment]
I think you're right that it must be related to spotify because I'm almost constantly listening to spotify. I don't think it's related to me manually switching tracks though because it seems to just happen over time

**Comment by ShankarBUS** [comment]
Then it's a duplicate of #100.

It will also crash if the track changes within the source app (such as Spotify)

**Comment by mgallub1** [comment]
OK I will close
