### ISSUE TITLE
Bug: If the appId returns empty show nothing instead of ModernFlyouts

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#140]
Under Media transport controls

**Comment by ShankarBUS** [comment]
Yes I know. It is intended?

The icon fetching is asynchronous and while it's happening instead of showing nothing, ModernFlyouts is shown.

After the info is returned (returns empty if the app couldn't be found), it will be shown there.

This means that the app fetching has some problems. My guess is it crashes halfway through. If it succeeds it will return either empty or the app's info

The ModernFlyouts icon should go away after a while. The method must have crashed. I'll look into it.

**Comment by yume-chan** [comment]
Last week I encountered this problem on Windows 10 insiders builds (I can't rememeber the build number, but must be the recent two or three builds).

When playing video in msedge, the `appId` from OS was an empty string (video title and control works). I tried both msedge stable and dev channels and both are same. On the other hand Groove Music works fine.

**Comment by ShankarBUS** [comment]
So bug is from the GSMTC APIs in Windows Insider builds?

If the appId returns empty, it means that the OS doesn't send it to us.

Or there could be some issues within our code 🤷‍♂️.

I will check it. Thanks yume-chan!

**Comment by Samuel12321** [comment]
> The icon fetching is asynchronous and while it's happening instead of showing nothing, ModernFlyouts is shown.

I personally think that its better to show nothing than an incorrect app.

I can confirm that it seems to be MS Edge specific (the new chromium one). Works fine with VLC and Films & TV

**Comment by ShankarBUS** [comment]
@Samuel12321,

> I personally think that its better to show nothing than an incorrect app.

I agree. I imagined myself as an intellectual being and thought it would be better if I just ModernFlyouts while the app info is being fetched 🤦‍♂️🤪.

It's easy, just a few lines of codes.

**Comment by ShankarBUS** [comment]
So, this issue has already been fixed. I'm going to close this now.
