### ISSUE TITLE
Feature Request: Add a way to start the app after every update.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#159]
**Is your feature request related to a problem? Please describe:**
After every update, the app is closed (for obvious reasons) and I have to start it again everytime from the Start menu.

**Describe the solution you'd like:**
Please add a way to start the app after every update.

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1,

I remember sending you links to the MS documentation for this feature on Telegram.

Could you resend me the links? I forgot the name of the API 😅.

**Comment by Cyberdroid1** [comment]
Sorry, I think our chat had got cleared some time back. The links might have been swept away with that...

**Comment by ShankarBUS** [comment]
I think could hell us https://www.codeproject.com/articles/74249/application-recovery-and-restart-c-quick-reference

**Comment by ShankarBUS** [comment]
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#restart-automatically-after-receiving-an-update-from-the-microsoft-store

Got it thanks @Cyberdroid1!

**Comment by ShankarBUS** [comment]
Got another one with complete code

https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates#automatically-restarting-your-app-after-an-update
😁

**Comment by ShankarBUS** [comment]
Did my best pals - 981017e4f726211e1c8c95188fdcf64f40aab15d

I'm still not 100% sure if this would work perfectly. As the app sometimes starts without a package identity when restarted programmatically [other than the startup task and manual launch by the user] some APIs misbehave quite often and may cause instabilities.

I don't know if this will work or not. We may need to wait till v0.8.3 (because this feature will be added to v0.8.2 and will only be valid in future updates) is released and updated via the Store to actually see if this works.

To check its validity it will show a message stating "App update successfully!" [only for v0.8.3 just to check if it works. I will remove this message in the future versions].

Let's hope it works 😅.
