### ISSUE TITLE
Feature Request: Add ability to control media with headset buttons

### ISSUE THREAD

**Issue by brkeejp** [ShankarBUS/ModernFlyouts#193]
I really like to see ability to control media with my headset buttons. (old 3.5 audio jack ones)

After a little search I found project named [AndroidMediaControlsWindows](https://github.com/roligheten/AndroidMediaControlsWindows) and looks not hard to me. (not sure about CS part)

I did really like to contribute but I don't familiar with CS also my current pc not good enough.

Thanks for reading.

**Comment by Samuel12321** [comment]
I thought windows had native support for this if your device had an audio jack that supports it.

**Comment by Samuel12321** [comment]
What do you think @ShankarBUS @Cyberdroid1

**Comment by Cyberdroid1** [comment]
I have a USB based headphones. Volume controls through that shows the modernflyouts. I don't have any AUX based that has media controls. So cant say.

**Comment by ShankarBUS** [comment]
So people are also having troubles with wireless headphones (#4).

I guess this issue asks us to support the audio jack inputs.

If Windows doesn't support it natively, there's nothing we can do 🤷‍♂️.

This issue can be closed if the Windows default flyout is not shown when the device's buttons are pressed.

**Comment by brkeejp** [comment]
Windows don't have support for this feature natively if you are using 4pin aux, but it's not a hardware issue.
Soo we can easily write supported application but no one did this publicly.

Tested with python code and result working like a charm.
Diagram:
![image](https://user-images.githubusercontent.com/35311303/98574330-d8bcfd80-22c8-11eb-93de-597610db5d3f.png)

Just asking can you guys do? Not like request but ask.

**Comment by ShankarBUS** [comment]
Well, we don't understand your request properly.

1. Do you just want to show the flyout?

2. Or control the volume using the headset/headphone/earphone inputs?

Showing the flyout is somewhat do-able.

But changing the volume using the buttons will be hard if Windows doesn't respond to the inputs.

Our aim is just to show a popup.

Not enable headphone buttons to change volume.

Can you currently change the volume using those buttons?

Is your request to just show the popup?

**Comment by brkeejp** [comment]
I wan it both.
if you press headset button Windows itself not catch the input so no event trigger meaning there is no popup.

Well I guess answer is; you can do but there is no meaning to do. Thanks anyway still best in class (also only one) for media popup.

**Comment by ShankarBUS** [comment]
I guess this request is out of our scope.

We just intend to show a popup, that's it.

However, your request is valid too.

If Windows doesn't receive the inputs natively, we may to need to write a driver manually and some program to actually control the volume first. We can't do anything if Windows doesn't even respect those inputs.

Are there any existing programs that can receive the input signals?

**Comment by ShankarBUS** [comment]
Wait wait, so does this project [AndroidMediaControlsWindows](https://github.com/roligheten/AndroidMediaControlsWindows) actually work for you?

If it works, then why are you requesting us to redo it?

**Comment by ShankarBUS** [comment]
Ok. So, these are my overall inferences.

- Earphone volume buttons does actually control the volume but the legacy flyout is shown instead of ModernFlyouts #4

- Your request is to use the media button in the earphone (which we use to end a call, play/pause media on Android) which Windows doesn't natively do.

I miss understood your statements 😅.

Are my current assumption correct?

So, the python program you suggested is what you need!

We don't need to redo the implementation ourselves.

The [AndroidMediaControlsWindows](https://github.com/roligheten/AndroidMediaControlsWindows) is enough to play/pause the media playback as it sends a media play/pause virtual key press signal.
ModernFlyouts must be compatible with that program.

What you need is ModernFlyouts to do the task, right?

My suggestion is we shouldn't add this feature to ModernFlyouts as it's completely different from our intentions.
