### ISSUE TITLE
Feature Request: Restart to apply settings

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#209]
Some settings changes specifically changing display language require ModernFlyouts to be restarted. For these settings there should be a button beside them to restart ModernFlyouts and apply settings.

**Comment by ShankarBUS** [comment]
I couldn't add a button to restart the app within the settings.
(Because restarting the app makes it run as an unpackaged app instead of a packaged one. It results in several major issues such as the app data being unavailable and functions which depends on a package identity throwing errors).

![image](https://user-images.githubusercontent.com/63704247/99569766-0c013a00-29f7-11eb-97e7-cd71a7236328.png)

I guess this would do the job for now 😅.
