### ISSUE TITLE
The commit merged by the pull request has been rolled back to the original version.

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [ShankarBUS/ModernFlyouts#249]
This commit...Why?
https://github.com/ShankarBUS/ModernFlyouts/commit/15e25fc76232e149c18892dc61d7ecdb50337452#diff-e1cc1d62206cc0373ab0a3b75e9c0e316ab1deab6937b05cb80f152b025b997c

**Comment by ShankarBUS** [comment]
We're really sorry 😅.

If you don't mind could you update those translations again.

Sorry for this merge issues.

We're relatively new to **"git"** and don't have any experience.
Merge issues and commit reversion is something we try to avoid.

But due to our lack of experience, we keep forgetting to sync our local clone before committing.

We will try to avoid this in the future.

**Comment by Poopooracoocoo** [comment]
#234 was the PR btw
