### ISSUE TITLE
Feature Request:Hope ModernFlyouts can provide 64bit version of the application

### ISSUE THREAD

**Issue by Gaoyifei1011** [ShankarBUS/ModernFlyouts#270]
希望ModernFlyouts可以提供64位版本的应用
Hope ModernFlyouts can provide 64bit version of the application

**Comment by ShankarBUS** [comment]
We do provide x64 bit build of this app since v0.8.2 (I don't know if it's out on the Store).

You may get a proper x64 build with the next release.

**Comment by Gaoyifei1011** [comment]
很好，我很期待在新的版本——0.8.2里看见64位的ModernFlyouts，希望也能够在Microsoft Store看见它发布
Very good, I am looking forward to in the new version - 0.8.2 saw 64bit ModernFlyouts, hope can also be released at the Microsoft Store to see it

**Comment by ShankarBUS** [comment]
Great! Thanks for your patience!

**Comment by Cyberdroid1** [comment]
@ShankarBUS 

I have seen this architecture mess up a lot of times. Sometimes, the app supports all 32, 64 bit CPUs, sometimes only 32. Why does it keep happening?

**Comment by Cyberdroid1** [comment]
> 希望ModernFlyouts可以提供64位版本的应用
> Hope ModernFlyouts can provide 64bit version of the application

If your PC has an Intel or AMD chip inside, it would run the app without any problem though.

**Comment by Gaoyifei1011** [comment]
我的电脑是Intel64位的
处理器	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

# To long; Didn't read:

Because we're still newbies!

# Unnecessary information (read this if you wanna waste your time like how I did writing this useless passage):

To be honest, I've never used any configuration other than **`AnyCPU`** previously.

.NET assemblies with **AnyCPU** configuration can run on any CPUs (it's pretty obvious).

The .NET bootstrapper (the normal *.exe built by the compiler) loads the appropriate runtime depending on the system's architecture (it does the work for us).

If we're to publish our app as **"framework independent"** [i.e. **.NET 5 runtime** (x64 or x86, it depends on the target system) has to preinstalled], we can just publish a small package (just 2 MB) with AnyCPU config. No additional work.

But we can't force the users to download and install the .NET runtime by themselves. They would just not use our app due to this burden. (Store could automatically do this. MSIX doesn't do this too. This is why Power Toys don't use the Store and MSIX)

v0.3 and prev were all based on **.NET Framework** (preinstalled on all Windows 10 OSes). So, we didn't have to force the users to install the **.NET runtime**.

It all started since we made the jump to **.NET Core**. Since then we are publishing this app as **"self contained"** (bundling a copy .NET runtime together with our app. Results in an increased package size 2 MB -> 60 MB) to reduce end users' burden.

While publishing as self contained we have to specify which runtime we are targeting (either x86 or x64). So no **`AnyCPU`** and no easy procedures. Thus we have to publish this app 2 times and the packager will bundle them into a mega package and provide the necessary package to the user.

@Samuel12321, hard coded the package to be x86 previously and we're smashing our heads at the wall wondering what went wrong.
**See #41**
Later we figured it out and fixed it during the v0.8.2 release 

The End!

**Comment by Cyberdroid1** [comment]
Gotcha! Sorry for making you type all that 😅. I feel sorry both for you and your computer's keyboard.

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

> Gotcha! Sorry for making you type all that 😅. I feel sorry both for you and your computer's keyboard.

Bruh! Why did you read all that??? I was in the toilet, got bored and typed all those in my mobile to just pass my time!
Anyways thanks for understanding our pain 😞😃.

**Comment by Samuel12321** [comment]
as @ShankarBUS said, fixed in 0.8.2, which you should get soon. (currently waiting on store certification)
