### ISSUE TITLE
Changes to default position stay that way only until the next system boot

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#274]
Store reported bug:

> When I change the default position it stays that way only until the next system boot - just a minor bug. Still love it ;)

**Comment by ShankarBUS** [comment]
There's no way this happens.

I have implemented methods to save and fetch both the flyout position and default position.

This could be bug with fetching the saved data due to regional formatting (someone already complained that the point is saved in "X**;Y" format instead of "X**,**Y").

I will fix this together with the fore-mentioned issue.

**Comment by Cyberdroid1** [comment]
Just simply add 2 separate boxes for X and Y instead of combined. Simple.

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

https://github.com/ShankarBUS/ModernFlyouts/issues/223#issuecomment-731700952

**Comment by ShankarBUS** [comment]
Let's continue with #223.
