### ISSUE TITLE
Making the scroll arrow button scroll a full card

### ISSUE THREAD

**Issue by msbrunoalves** [ShankarBUS/ModernFlyouts#3]
Hello, would you be able to make the scroll arrow buttons scroll exactly 1 player card? Right now they scroll like 1/5th of the card and it's not of much use other than visual help.
I know you can scroll with the mouse but because the UI is there sometimes it's just instinct to click the arrow.
![image](https://user-images.githubusercontent.com/50234199/87231175-bb286780-c3ac-11ea-93bd-437dfcdcc4d5.png)

Thank you, really loving this app.

**Comment by ShankarBUS** [comment]
I was thinking of the same, but it would scroll abruptly and won't have animations as in UWP

**Comment by ShankarBUS** [comment]
I tried modifying it and It will now scroll 1 item at a time. And the buttons will hide when they are not needed

But there are several limitations :
- It will scroll abruptly and won't be smooth
- Since items can expand they may behave incorrectly
- Mouse scrolling will also scroll 1 item at a time 🤷‍♂️

**Comment by ShankarBUS** [comment]
It has been [implemented](https://github.com/ShankarBUS/ModernFlyouts/commit/7ab5bc9307bac2188d8e94875a6451301ae67cd4) and will be available in the next release.
