### ISSUE TITLE
System panels do not work after uninstalling the application.

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#34]
Just got a very vague and worrying review on MS Store "System panels do not work after uninstalling the application."
Have asked the user to provide more information.

**Comment by ShankarBUS** [comment]
"System panels" I guess they meant the OS provided flyout UI not being visible.

If so, it could be fixed by either restarting/signing out and in/restarting explorer.exe

This is not really a issue to worry about. Our flyout overrides the default one and hides it (it shouldn't but at the start it will hide the OS default one and will unhide them when were unable to handle the scene. This could also be experienced when you close the app suddenly from task manager) and when uninstalling the original one is not restored.

There is a simple fix for this. Should this be fixed right now?

**Comment by ShankarBUS** [comment]
Hey @Samuel12321, this bug be fixed once we have the FlyoutManager app (a C++ executable that will watch the ModernFlyouts process and will restore the original one in case our app crashes & will quit itself later).

@ADeltaX is taking care of it. Don't know the exact timeframe for this but it will be available before v1.0

**Comment by ShankarBUS** [comment]
We also have the "Restore Default" option in v0.5.0 which will start ModernFlyouts, restores the Windows default one and closes our app. It will be an intermediate solution for this bug.

**Comment by ShankarBUS** [comment]
Hey @Samuel12321 fyi, we need to fix this issue and #32 in **v0.7**

I will start working on this after we release **v0.6**

So we need to move everything planned for **v0.7** to **v0.8** 
**v0.7** - make flyout **topmost**, automatically **restore windows stock flyout** after **crashes** and **docs** [wiki & images]
(this could break the jumplist & startup tasks, app config and many things. So we won't be able to add any new features)

**v0.8** - mostly reorg in settings and some UI updates

**Comment by ShankarBUS** [comment]
Since we have the "Exit" & "Restore legacy flyouts" option and a proper uninstallation procedure on the How-To's wiki page, I'm closing this issue as fixed.

I guess these options are sufficient for the users who prefer a clean uninstallation experience.

The fore-mentioned multi-process architecture will be implement in the future to expand support for proper usability and stability of ModernFlyouts and to show it topmost.

I will try my best to make this app safe and usable to general users.
