### ISSUE TITLE
Proposal: Explore future migration to WinUI

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#45]
Will allow additional features such as acrylic.

**Comment by ShankarBUS** [comment]
WinUI 3 neither have acrylic nor reveal 😂. We have to use xaml islands until they support them.

There won't be acrylic or reveal in WinUI 3. It is planned for WinUI 4? Which will be released in 2021-2022.

So for a immediate need we can switch to WinUI 2 and xaml islands

**Comment by ShankarBUS** [comment]
Even if we switch to WinUI 2 xaml islands, I don't know how we are gonna create the flyout. For settings window there won't be any problems. The flyout is going to be a tricky one.

**Comment by Cyberdroid1** [comment]
There can be blur too with XAML islands, right?

**Comment by ShankarBUS** [comment]
Yes! That's what I said (xaml islands + WinUI 2).

We can have proper acrylic effect only if we use xaml islands (not present in WinUI 3 so we can use WinUI 2 xaml islands)

But the problems are (applies to both WinUI 2 & WinUI 3) :

- No modern window border, title bar (chrome) in settings (a similar issue can be found in PowerToys)

- No rounded corners/shadows in the flyout (could have rounded corners but it won't be good)

- No animations while showing/hiding flyout (since WinUI 2 & 3 won't supports transparent alpha blended windows)

- Not sure whether it will be fast/slow. BUT Since the UI is in WinRT and our code being in .NET the communication between two runtimes could be slow (still not sure)

**Comment by Cyberdroid1** [comment]
It would lead to the same static look like that in windows default flyout, right?

**Comment by Samuel12321** [comment]
done some work on the multi language support, unfortunately it appears to be rather difficult in WPF, in winUI and UWP it can be partially automated. Another thing to keep in mind when considering future options.

**Comment by ShankarBUS** [comment]
Yes that's why I'm hesitant to add multi-lingual support. Too much work for a feature that no one bother not having.
Let's see if somehow find an efficient way 🤷‍♂️

**Comment by Samuel12321** [comment]
Closing as not useful unless WinUI adds rounded corners and acrylic as well as the others mentioned above.
None of which are planned in the near future.
