### ISSUE TITLE
Move cover art to left of media flyout

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#49]
This is a pre-emptive decision, but I believe that Microsoft will do this as Google has done this on Android and will soon do so on Chrome, and therefore Edge. 

<details>
<summary>random rant that you shouldn't read</summary>

it's funny that chrome's global media controls (GMC) get updated more frequently than windows' system media transport controls (SMTC). 
the GMC goes unchanged in edge too and yet only edge has a bug where the icon of a button doesn't change until you move your cursor away from it. lol. 
still can't seek in the GMC or SMTC >:(
i really think google just saw ios and thought "ooh nice", especially with the "seamless media transfer"
</details>

**Comment by ShankarBUS** [comment]
The original design had the thumbnail on the left 😂. Had to align the UI with Windows 10X so that people won't complain **"wInDowS 10 is InCOnSisTEnt"**.

IMO, keeping the thumbnail on the right looks good UX wise. Because most of the people are used to LTR layouts. It is away from the text and looks noice.

I do agree keeping it on left is good. And if Google or Apple make a design doesn't mean Microsoft must copy it. Gotta do something different, different people prefer different things.

I will update the UI along with whatever design MS choose.

But that must not stop users from customising to their own taste.

So as for your case I can provide an option to align it to the **"Left"**.

**Comment by Poopooracoocoo** [comment]
>And if Google or Apple make a design doesn't mean Microsoft must copy it

Microsoft doesn't have to but they probably will as they will probably want it to fit in with Edge. Edge could change the GMC but they haven't now, so why would they later? :p

The LTR argument could be made for the cover art being on the left. I don't mind whether the cover art is on the left or right tbh.

**Comment by ShankarBUS** [comment]
If the thumbnail was on the left the layout will look crowded on the left. There will empty space on the right since not every media session is gonna have a long title. So I had to take the decision of keeping it on the right.

But I promise i will provide a way to customize it.

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

> still can't seek in the GMC or STMC >:(

We can actually seek the playback **iff** the source app supports seeking through **SMTC**. Currently we only have a **ProgressBar** to show the timeline properties. We could replace that with a slider to actually control the playback from our app. But the last time I tried, it was really **slow**. I will reconsider this in future versions

**Comment by ShankarBUS** [comment]
@Poopooracoocoo, HmMmMMmMmmmMmMMm 🤔🤔🤔

![image](https://user-images.githubusercontent.com/63704247/97695008-63337f00-1ac9-11eb-94a2-11d7c336f161.png)

What about this? U happy?

**Comment by Samuel12321** [comment]
is this user changeable, i personally preferred it as it was. However it is good.

**Comment by Samuel12321** [comment]
perhaps have the background image cover the width of the flyout (not stop a cm from the right side) and blur out like it does on the left side

**Comment by ShankarBUS** [comment]
> is this user changeable

Yup! Users can customize it.

> i personally preferred it as it was

It will be aligned to right by default. I provided an option to switch it just because @Poopooracoocoo asked for it.

> perhaps have the background image cover the width of the flyout (not stop a cm from the right side)

This is an issue with Spotify. It provides the thumbnail with pre-added padding and label. There's nothing we can do about it 🤷‍♂️

> blur out like it does on the left side

Oh!!!!!!, I never thought of this. The fading should switch together with switch in thumbnail alignment.

**Comment by ShankarBUS** [comment]
@Samuel12321, Is it okay now?

![image](https://user-images.githubusercontent.com/63704247/97697370-edc9ad80-1acc-11eb-981f-fc2c803a9828.png)

**Comment by Poopooracoocoo** [comment]
Great work! Thank you so so very much for this and for ModernFlyouts! 😀

**Comment by Samuel12321** [comment]
Looks Great

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

Thanks for opening this feature request!

Your request has been implemented in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56.

Please give v0.8 a try once its available to you via MS Store or this repo.

Please give us more suggestions, feedbacks, ideas or bug reports in the future 😁.

My lazy ass brain couldn't come up with new ideas. So, I must admit that the community really guided me since v0.2 release (be bugs or new features).

I'm really happy to people that like and want this app to sustain and grow ❤.
