### ISSUE TITLE
Trying to delete the "comma" in flyout postion crashes the app

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#52]
When trying to change the coordinates, when trying to delete the comma with a backspace, it crashes the app. 

It would be better to either fix this issue or create separate boxes for the same.

**Comment by ShankarBUS** [comment]
Found it out huh! I tried to escape with it 🤣. This is just a base implementation. Will fix it later to show a red outline around the textbox. But the separate text box idea is better and easier than the former 👏

**Comment by ShankarBUS** [comment]
Done! ca7f16f16fb2450ac6b46b024f624160e3b93c3c

Please wait till v0.6.0 is released 😁

**Comment by Cyberdroid1** [comment]
Red borders or separate boxes? I see red boxes in code.

**Comment by ShankarBUS** [comment]
Red box 😁

Unfortunately, it's hard to detect the X or Y value changes for a point (Since it's a `struct` not a `DependencyObject`). So we had to change the point as a whole and not its X, Y value.

So we had to go with a single TextBox 😅. We can still implement 2 textboxes which will generate a `Point` but I went with easiest approach.
