### ISSUE TITLE
Feature Request: Option to set dark theme / light theme / system default

### ISSUE THREAD

**Issue by neubland** [ShankarBUS/ModernFlyouts#75]
Right now it seems like system default is automatically used. This is fine and a good default. Many apps let you choose whether to use system default or manually override with dark/light theme. This would be nice for ModernFlyouts.

**Comment by ShankarBUS** [comment]
The problem is where should that setting apply to??

We have the flyout following System Theme (would be similar to TaskBar, ActionCenter & etc) and the Settings Window following App Theme (would be similar to other apps)

Should there be two options? Like
**Flyout theme :**
[x] Dark
[] Light
[] System Default

**Settings Theme :**
[x] Light
[] Dark
[] System Default

Since Windows 8, the inbuilt flyout is dark. Most of the apps are light by default. That's why I switched them above.

Currently the settings window is so cluttered and unorganized. This may be a priority for v0.10.0

**Comment by neubland** [comment]
To be honest, I don't want to customize the settings page, I want to customize the flyout, and only the flyout. I propose the option to change the flyout theme and leave the settings theme untouched (which is following app theme, I gather?). Optimally a user uses the settings page on first use and rarely after that anyway.

**Comment by ShankarBUS** [comment]
I know for sure you would say this. I wanted to actually implement this feature in v0.1.0 but dropped the idea (Since then this project didn't have much of attention or users). Would reconsider this 😁

**Comment by ShankarBUS** [comment]
@neubland,

Your request is implemented in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56.
Thank you so much for opening this feature request. Please give us new suggestion and ideas or file bug issues if you have time in the future 😄. Seeing and interacting with active users on GitHub motivates us to improve this app. Thanks again for giving our app a try 😁.
