### ISSUE TITLE
Media flyout doesn't show for musicbee or plex 

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#79]
Store feedback

**Comment by ShankarBUS** [comment]
Do the inbuilt media flyout support those apps?

If they don't support them, there's nothing we can do about.

Same applies to VLC Media player.

I previously did a PR on the Dopamine-Windows, so that we can have a better integration.

If those apps are open source, we can do something on their side.

Our side is complete. Any app that uses `SystemMediaTransportControls` is supported by ModernFlyouts.

**Comment by Samuel12321** [comment]
Just checked, plex doesn't use the built in flyout. Not sure about musicbee.

Created a feature request on the Plex Media Player site.

**Comment by ShankarBUS** [comment]
Yes! That's great. Using `SystemMediaTransportControls` will not only enable integration with our app but also with Windows OS.

**Comment by Samuel12321** [comment]
Will close for now as this doesn't appear to be a Modern Flyouts issue.
