### ISSUE TITLE
Lock keys flyouts do not respect PowerToys Keyboard Manager

### ISSUE THREAD

**Issue by watermarkhu** [ShankarBUS/ModernFlyouts#84]
If for example the Caps Locks and Left Control are remapped to each other in the PowerToys Keyboard Manager, pressing Caps Lock still enables the flyout. Also, if the key is remapped, the value of the lock key in ModernFlyout is flipped, while the real value hasn't changed. 

Example if the CapsLocks and Left Control are remapped:

**CapsLock real value**, _ModernFlyout value_

**CapsLock is on**:   CapsLock -> _CapsLock is off_, CapsLock -> _CapsLock is off_, Left Control: **CapsLock is off** -> _CapsLock is off_
**CapsLock is off**:   CapsLock -> _CapsLock is on_, CapsLock -> _CapsLock is on, Left Control: **CapsLock is on** -> _CapsLock is on_

**Comment by ShankarBUS** [comment]
Thanks for filing this issue! But unfortunately I can't reproduce the behaviour with your said information.
![image](https://user-images.githubusercontent.com/63704247/95068765-510d2d80-0723-11eb-80b6-85e55cdf7593.png)

It's working as intended for me. Could you provide a detailed example?

This problem could be arising due to ModernFlyouts starting way before PowerToys.
We both use [**"Low Level Keyboard Hook"**](https://github.com/ShankarBUS/ModernFlyouts/blob/49b249a798c6f4aca4443e46a816aa5f593b89c8/ModernFlyouts/Classes/KeyboardHook.cs#L62) so if ModernFlyouts starts first, it will hook first and won't respect the changes PowerToys introduce.

Since the hook is passed based on priority the first one receives the key before others. PowerToys hooks to the key changes, stop them from passing to other apps & sends other key based on the user's preferrences.

Thus, ModernFlyouts is triggered two times (once by key press & once by PowerToys key redirection). There is nothing we can do about 🤷‍♂️.

One solution would be to start ModernFlyouts after PowerToys has been started and running

**Comment by watermarkhu** [comment]
Starting ModernFlyouts before PowerToys does fix this issue. I've made sure that they are started in this sequence in Task Scheduler and now is working as intended. Thank you for the reply!
